$(document).ready(function(){
  $("#design").click(function(){
    $(".designIcon").toggle();
    $(".pDesign").toggle();
  });
  $("#devs").click(function(){
    $(".devIcon").toggle();
    $(".dment").toggle();
  });
  $("#management").click(function(){
    $(".prodIcon").toggle();
    $(".product").toggle();
  });


  $(".image1").hover(function(){
  
    $(".text1").toggle();
  });
  $(".image2").hover(function(){
    $(".text2").toggle();
  });
  $(".image3").hover(function(){
    $(".text3").toggle();
  });
  $(".image4").hover(function(){
    $(".text4").toggle();
  });
  $(".image5").hover(function(){
    $(".text5").toggle();
  });
  $(".image6").hover(function(){
    $(".text6").toggle();
  });
  $(".image7").hover(function(){
    $(".text7").toggle();
  });
  $(".image8").hover(function(){
    $(".text8").toggle();
  });
});
